# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/schema/schema.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'ai/schema/schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61i/schema/schema.proto\x12\x13\x61ttention_span_data\"\xb6\x01\n\rUserAttention\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x0b\n\x03\x41ge\x18\x02 \x01(\x03\x12\x0e\n\x06Gender\x18\x03 \x01(\t\x12\x11\n\tResidence\x18\x04 \x01(\t\x12;\n\nReason_las\x18\x05 \x01(\x0e\x32\'.attention_span_data.LowAttentionReason\x12\x12\n\nScreentime\x18\x06 \x01(\x02\x12\x16\n\x0e\x41ttention_Span\x18\x07 \x01(\x02*\xea\x01\n\x12LowAttentionReason\x12$\n LOW_ATTENTION_REASON_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x46\x41MILY_PROBLEMS\x10\x01\x12!\n\x1dLACK_OF_SLEEP_AND_POOR_HEALTH\x10\x02\x12\x10\n\x0cMULTITASKING\x10\x03\x12\x16\n\x12STRESS_AND_ANXIETY\x10\x04\x12\x10\n\x0cRELATIONSHIP\x10\x05\x12 \n\x1cSMARTPHONES_AND_SOCIAL_MEDIA\x10\x06\x12\x18\n\x14LACK_OF_GOAL_CLARITY\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.schema.schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOWATTENTIONREASON']._serialized_start=233
  _globals['_LOWATTENTIONREASON']._serialized_end=467
  _globals['_USERATTENTION']._serialized_start=48
  _globals['_USERATTENTION']._serialized_end=230
# @@protoc_insertion_point(module_scope)
